name: EvStats
main: net.evmodder.EvStats.EvStatsMain
author: EvModder
website: https://github.com/EvModder/EvStats
description: Auto-generate scoreboards for a bunch o' stats
version: 1.0
api-version: 1.13

# IIUC, softdepend will prefer loading these plugins BEFORE loading EvStats
softdepend: [DropHeads, PlayerHeads, HorseOwners, ChatManager, Votifier]

commands:
  stat:
    description: Display a given statistic on the scoreboard
    usage: /stat <stat> [time] [entry]
    aliases: [stats,statistic,statistics]
    permission: evstats.command.statistics
    permission-message: You do not have permission to do this.

  register_scoreboards:
    description: Registers (or renamed) all enabled scoreboards
    usage: /register_scoreboards
    permission: evstats.command.register_scoreboards
    permission-message: You do not have permission to do this.

permissions:
  evstats.command.statistics:
    description: Permission to use /stat
    default: true

  evstats.command.register_scoreboards:
    description: Permission to use /register_scoreboards
    default: op